# Commands
commands:
  version:
    aliases: [ver]
    permissions:
      - cubDialogs.admin.version
  reload:
    aliases: [rl, restart]
    permissions:
      - cubDialogs.admin.reload
  open:
    aliases: [op]
    permissions:
      - cubDialogs.admin.open
  validate:
    aliases: [val]
    permissions:
      - cubDialogs.admin.validate
  help:
    aliases: [h]
    permissions:
      - cubDialogs.admin.help
  forceopen:
    aliases: [fo]
    permissions:
      - cubDialogs.admin.forceopen
  forceclose:
    aliases: [fc]
    permissions:
      - cubDialogs.admin.forceclose