name: CubDialogs
version: ${version}
main: io.github.devbd1.cubDialogs.Main
api-version: '1.21'
load: STARTUP
authors: [ DevBD1 ]
description: Spigot development library, built for the latest version.
website: https://cublex.net
softdepend:
  - PlaceholderAPI
#  - CubItems
#  - CubLoots
#  - CubSense
#  - CubConquest
#depend:
  - CublexCore
commands:
  cubDialogs:
    aliases: [cdia]
    permission: cubDialogs.command.main
    permission-message: You don't have permission to use this command.
    usage: /<command>
permissions:
  cubDialogs.command.main:
    default: true
    description: Allows you to use the main command.
  cubDialogs.admin.version:
    default: op
    description: Allows you to see the plugin version.
  cubDialogs.admin.reload:
    default: op
    description: Allows you to reload the plugin.
  cubDialogs.admin.open:
    default: op
    description: Allows you to open dialogs.
  cubDialogs.admin.validate:
    default: op
    description: Allows you to validate dialogs.
  cubDialogs.admin.help:
    default: op
    description: Allows you to see the help.
  cubDialogs.admin.forceopen:
    default: op
    description: Allows you to force open dialogs for others.
  cubDialogs.admin.forceclose:
    default: op
    description: Allows you to force close dialogs for others.
